### ISSUE TITLE
Incomplete linear algebra functions (raymath)

### ISSUE THREAD

**Issue by buckle2000** [onroundit/raylib-d#12]
This binding doesn't include math functions raymath has.

**Comment by onroundit** [comment]
:ballot_box_with_check: Thanks for binding!

**Comment by buckle2000** [comment]
It's not binding. I used language features in D. For example,

**Comment by buckle2000** [comment]
Also, the API is unstable. Please don't publish this just yet.

**Comment by profan** [comment]
Any reason you're not just binding raymath directly?

I decided to just fork this repo and directly bind raymath instead on my end (also undefining the rotor3/etc), not using the other (incomplete) math functions this has.

I feel like if you want to make extra math functions that belongs in a separate thing still.

**Comment by buckle2000** [comment]
Most because D has more features. I'd rather write `a + b` than `Vector2Add(a, b)`

**Comment by profan** [comment]
The operator overloading argument makes sense, but there's just a whole heckton of missing functions that are necessary if you want to do any 3D with this binding right now so it would make more sense to just add all the bound functions first so people can use it, then afterwards add the operator overloads/niceties to the structures.

But that's just my opinion though, not like i can force you of course :P

**Comment by buckle2000** [comment]
Please merge the bindings of raymath you made. I'll rename the syntax sugar version to `raylib.math`.

**Comment by profan** [comment]
I'll PR it right after work :+1:

**Comment by m3m0ry** [comment]
Providing some simple Vector data types would be great. I have already some of my own.
You can steal some sugarry syntax from my [https://github.com/m3m0ry/slinkshotwars/blob/master/source/data.d](Vector struct)

**Comment by buckle2000** [comment]
@m3m0ry we already have that for every linear algebra type. Check in `src/raylib/math.rs`.

**Comment by qbaddev** [comment]
.

**Comment by xdrie** [comment]
i have submitted #15 that should add the bindings.
