### ISSUE TITLE
Raylib-d is missing Color and Key constants

### ISSUE THREAD

**Issue by xgnell** [onroundit/raylib-d#20]
Hi, I really love raylib and the D programming language, glad to see raylib-d are keeping up to date. However, I think it is missing some constants. When I ran my program, these errors appeared:

ddmp 0.0.1-0.dev.3: target for configuration "library" is up to date.
stdx-allocator 2.77.5: target for configuration "library" is up to date.
libdparse 0.14.0: target for configuration "library" is up to date.
fluent-asserts 0.13.3: target for configuration "library" is up to date.
runner ~master: building configuration "application"...
source/app.d(36,30): Error: undefined identifier BLACK
source/app.d(40,29): Error: undefined identifier RAYWHITE
source/app.d(42,27): Error: undefined identifier KEY_A
source/app.d(44,34): Error: undefined identifier KEY_D
source/app.d(48,27): Error: undefined identifier KEY_W
source/app.d(50,34): Error: undefined identifier KEY_S

I hope you can fix them soon :))

**Comment by onroundit** [comment]
Hi! The constants have been moved to the enumerations.
You should use it this way:
Colors.BLACK
KeyboardKey.KEY_RIGHT
