### ISSUE TITLE
Raylib: compiler does not recognize input keys - "undefined identifier KEY_RIGHT" etc...

### ISSUE THREAD

**Issue by rillk500** [onroundit/raylib-d#4]
I am using dmd compiler and dub to manage my project. I want to process keyboard events, however, compiler does not recognize any of the keys. I follow the official raylib examples and everything worked just fine until i tried to get the input key. 

Compiler produces the following:
`source/app.d(21,23): Error: undefined identifier KEY_RIGHT
source/app.d(22,23): Error: undefined identifier KEY_LEFT
source/app.d(23,23): Error: undefined identifier KEY_UP
source/app.d(24,23): Error: undefined identifier KEY_DOWN`

Here is the code:
`import raylib;

void main() {
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [core] example - keyboard input");

    Vector2 ballPosition = { screenWidth/2, screenHeight/2 };

    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        if (IsKeyDown(KEY_RIGHT)) ballPosition.x += 2.0f;
        if (IsKeyDown(KEY_LEFT)) ballPosition.x -= 2.0f;
        if (IsKeyDown(KEY_UP)) ballPosition.y -= 2.0f;
        if (IsKeyDown(KEY_DOWN)) ballPosition.y += 2.0f;
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("move the ball with arrow keys", 10, 10, 20, DARKGRAY);

            DrawCircleV(ballPosition, 50, MAROON);

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------
}`

Thanks in advance.

**Comment by onroundit** [comment]
Hello! I should have explained it somewhere, in C, enumerations have global visibility.
In D enums have their own scope. Therefore, you need to use this: `KeyboardKey.KEY_RIGHT`.

**Comment by rillk500** [comment]
It works! Thank you!
