### ISSUE TITLE
Linking issues

### ISSUE THREAD

**Issue by m3m0ry** [onroundit/raylib-d#5]
Hello,

i am confused how to properly link against raylib.
I can compile from source, or use the provided precompiled versions.
The examples of raylib work fine.

I have added the `"libs" : ["raylib"]` to the `dub.json`.
First, i placed the .a and .so into the main folder of my project, receiving this:
```
Linking...
/usr/bin/dmd -of.dub/build/application-debug-linux.posix-x86_64-dmd_2089-45764C16B2C8B9D0566F02F30C2B124B/slinkshotwars .dub/build/application-debug-linux.posix-x86_64-dmd_2089-45764C16B2C8B9D0566F02F30C2B124B/slinkshotwars.o ../../../.dub/packages/raylib-d-2.5.0/raylib-d/.dub/build/library-debug-linux.posix-x86_64-dmd_2089-4B596E1F55A61C7DAA359DF2A5338D7D/libraylib-d.a -L--no-as-needed -L/home/hrom/git/d/slinkshotwars/linux-amd64/ -L-lraylib -g
/usr/bin/ld: cannot find -lraylib
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```
I also tried to `make install` the raylib library. (`cmake -DSHARED=ON -DSTATIC=ON ..`)
This then compiles, but i receive the following:
```
Performing "debug" build using /usr/bin/dmd for x86_64.
raylib-d 2.5.0: target for configuration "library" is up to date.
slinkshotwars ~master: building configuration "application"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./slinkshotwars 
./slinkshotwars: error while loading shared libraries: libraylib.so.251: cannot open shared object file: No such file or directory
Program exited with code 127
```

What am i missing?

**Comment by m3m0ry** [comment]
The raylib library should be correctly in `user/local/lib/`:
```
ls /usr/local/lib/lib*
/usr/local/lib/libraylib.a   /usr/local/lib/libraylib.so.2.5.0
/usr/local/lib/libraylib.so  /usr/local/lib/libraylib.so.251
```

I also don't understand, why it needs the dynamic library at all.
(but i also lack on knowledge regarding static and dynamic binding)

**Comment by m3m0ry** [comment]
Ok, if i set manually: `export LD_LIBRARY_PATH=/usr/local/lib`
Then it works.

I really don't understand why my `/usr/local/lib` is not in my library path? Because, it should be:
```
> cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib
```

**Comment by onroundit** [comment]
Hello!
about the problem with the linker, I’ll try to study the behavior of the dub in more detail.
About bindings. A static library is used to define library symbols. In this case, you can use the dynamic library for runtime or force the dub to statically compile.

**Comment by onroundit** [comment]
I met several similar problems on the D programming language forum. But I personally have not met this problem since I put all the necessary libraries into the root of the dub project.

**Comment by m3m0ry** [comment]
I could reproduce this problem on a computer at work.
The fix is just exporting the proper path. (So if i download the raylib2.so, i just set the `LD_LIBRARY_PATH` to that folder).
However i am still confused, why the computer at home did not load the library from `/usr/local/lib`.

**Comment by o3o** [comment]
I think you shouldn't use (
```
// dub.sdl
"libs" : "raylib"
```

but
```
// dub.sdl
 lflags "-L/your/raylib/path" "-lraylib"
```

See my [example](https://github.com/o3o/d_static_binding)

**Comment by m3m0ry** [comment]
Yes, this fixes the build process.
However for the execution the loader still need the `LD_LIBRARY_PATH` being set to the proper folder.
Can i set it somehow also directly in the executable, so the loader will find it?

(This issue is thus definitely not an issue of this library. It has to do with my little understanding of dub and the linking/loading process of an executable.)

**Comment by m3m0ry** [comment]
Alright. The planets just aligned (or i rebooted my computer) and now it works, without any sets of `LD_LIBRARY_PATH`.

**Comment by Airbus5717** [comment]
```shell
Performing "debug" build using :\Programs\dlang\dmd\D\dmd2\windows\bin64\dmd.exe for x86_64.
ddmp 0.0.1-0.dev.3: target for configuration "library" is up to date.   
stdx-allocator 2.77.5: target for configuration "library" is up to date.
libdparse 0.14.0: target for configuration "library" is up to date.     
fluent-asserts 0.13.3: target for configuration "library" is up to date.
raylib_firstwindow ~master: building configuration "application"...     
Linking...
LINK : fatal error LNK1104: cannot open file 'raylib.lib'
Error: linker exited with status 1104
:\Programs\dlang\dmd\D\dmd2\windows\bin64\dmd.exe failed with exit code 1.```

i get this on win10
