### ISSUE TITLE
Document how to use this library

### ISSUE THREAD

**Issue by leotada** [onroundit/raylib-d#8]

**Comment by leotada** [comment]
I was able to build only with this configuration in dub.json:
`"lflags": ["path/libraylib.so"]`
and to run I have to put the raylib in the $LD_LIBRARY_PATH.

**Comment by onroundit** [comment]
Instructions are written in README.md, but I tested only in Windows. I will fix many things after updating the bindings to new version.

**Comment by m3m0ry** [comment]
You can check out this youtube channel for more raylib stuff: https://www.youtube.com/channel/UCK3fxU3_7tzBhZZ_6rljAQA

There is an "installation video", but there is no answer to your question.
Your question (i guess) is about "How do I install raylib (the c library) so the building and executing of my project finds it"
This is all about the linker and loader you are using. (So nor Dlang neither raylib-d specific)
I have put the library files into `/usr/local/lib` and the one header file into `/usr/local/include` (just copied them from the extracted raylib folder with `sudo` to thos folders.
You might need to run `sudo ldconfig` afterwards.
Also check that your linker and loader actually look into `/usr/local/*`.

**Comment by m3m0ry** [comment]
I am not sure myself what the "correct" way of doing things is.
Since it is not `raylib-d` specific, maybe we could pack this information into the wiki of this repository?

**Comment by onroundit** [comment]
> I am not sure myself what the "correct" way of doing things is.
> Since it is not `raylib-d` specific, maybe we could pack this information into the wiki of this repository?

Yeah, it'll have to be on the wiki.
But I'm too busy right now, I'm working on some big projects for one company. I'm almost done with them, but I can't update the repository now. Maybe you can help.

**Comment by m3m0ry** [comment]
I can clone the wiki, but I cannot create PR of the wiki.
I have searched on the internet and the current suggested approach is to fork the repo, create a wiki, force pull the original wiki, make changes, and then write an email, or create an issue you, so you, the creator of the original wiki cherry-picks the change.
Wow, this sucks. First time Github disappoints me.

And alternative would be to grant everyone [permission to the wiki](https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis).

Or you can add me as a collaborator. Then i can edit wiki and the repository directly, without any PRs.

So now you need to decide, whether you want to have pain with git cherry-picking :cherries:, trust the community not to destroy your wiki, or trust me not to destroy the repository. :dagger: 
:rofl: 
I would go with option B.

**Comment by onroundit** [comment]
> Or you can add me as a collaborator. Then i can edit wiki and the repository directly, without any PRs.

I sent you an invitation. Thank you!

**Comment by m3m0ry** [comment]
I have added a new Wiki page: https://github.com/onroundit/raylib-d/wiki/Installation
I have added an example project: https://github.com/onroundit/raylib-d/tree/master/example

I hope it was ok.

**Comment by m3m0ry** [comment]
@leotada I hope i have answered the question.
